### ISSUE TITLE
Add a License to the Project

### ISSUE THREAD

**Issue by Edmondi-Kacaj** [UsmanLiaqat404/dashcode-nextjs-admin-template#1]
Hello,

We are interested in using your project but noticed it lacks a license. Without a license, we cannot use, modify, or distribute the project. Please add a license to clarify the terms of use.

You can choose from options like MIT, Apache 2.0, or GPL v3.0. GitHub's guide on choosing a license might be helpful: https://choosealicense.com/.

Thank you.

**Comment by UsmanLiaqat404** [comment]
Hello,

Thank you for your interest in using my project. I appreciate you bringing this to my attention. I have now added the MIT License to the repository to clarify the terms of use.

You can view the [LICENSE](https://github.com/UsmanLiaqat404/dashcode-nextjs-admin-template/blob/main/LICENSE) here.

If you have any other questions or need further assistance, feel free to reach out.

Best regards
Usman Liaqat
